<?php
$content .= "How to Set Reminders <br /><br />

Bumper schedules your reminders based on the email address you use to set them. <br /><br />

For example if your catchall domain was bumper.cc, sending an email to thursday@bumper.cc would schedule Bumper to send that email back to you next Thursday. Note that Bumper reads the BCC field for this address, so you must use that field to schedule your reminder. <br /><br />

This also means you can reply to an email and schedule a reminder at the same time. <br /><br />

The list below contains examples of the six different ways you can format your scheduling request when BCC'ing Bumper to set a reminder. <br /><br />

Date, or date-time of day. <br /><br />

BCC july14@bumper.cc to have the email sent back to you on July 14th (3PM by default.) <br /><br />

BCC september20-3pm@bumper.cc to have the email sent back to you on September 20th at 3pm. <br /><br />
Day of week, or day of week-time of day. <br /><br />

BCC thursday@bumper.cc to have the email sent back to you on Thursday (3PM by default.) <br /><br />

BCC tuesday-9.30am@bumper.cc to have the email sent back to you on Tuesday at 9:30 AM. <br /><br />
Time from now, or time from now + time of day. <br /><br />

BCC 2weeks2days3hours5minutes to have the email sent back to you in 2 weeks, 2days, 3 hours and 5 minutes from now. <br /><br />

BCC 1year2days10minutes to have the email sent back to you in 1 year, 2days and 10 minutes from now. <br /><br />

BCC 2months8am to have the email sent back to you in 2 months at 8 am. <br /><br />

BCC 1week2days12pm to have the email sent back to you in 1 week and 2 days, at 12 noon. <br /><br />

Note that when combining time from now + time of day, you can use years, months, weeks and days + a time of day. Time of day replaces hours and minutes.";